# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - ci
  - ts # run unit test of sonarts-core with different TypeScript versions
  - plugin
  - ruling

SQ_VERSION:
  - DEV
  - LATEST_RELEASE
  - LTS

exclude:
# exclude CI on linux, because it was already done on travis
  - TEST: ci
    SLAVE: linux
# limit Windows CI and plugin tests only to LATEST_RELEASE
  - SLAVE: windows
    SQ_VERSION: DEV
  - SLAVE: windows
    SQ_VERSION: LTS

# limit Ruling test to Linux/LATEST_RELEASE only    
  - TEST: ruling
    SLAVE: windows
  - TEST: ruling
    SQ_VERSION: DEV
  - TEST: ruling
    SQ_VERSION: LTS

# limit ts test to only one run (we don't care about OS and SQ)
# run only on linux + LTS
  - TEST: ts
    SLAVE: windows
  - TEST: ts
    SQ_VERSION: DEV
  - TEST: ts
    SQ_VERSION: LATEST_RELEASE
