# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - ci
  - plugin

SQ_VERSION:
  - DEV
  - LATEST_RELEASE
  - LTS

exclude:
# exclude CI on linux, because it was already done on travis
  - TEST: ci
    SLAVE: linux
# limit Windows CI and plugin tests only to LATEST_RELEASE
  - SLAVE: windows
    SQ_VERSION: DEV
  - SLAVE: windows
    SQ_VERSION: LTS
