# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

TEST:
  - ci
  - plugin
  - ruling

SQ_VERSION:
  - DEV
  - LATEST_RELEASE
  - LTS

exclude:

  - SLAVE: linux
    TEST: ruling

  - SLAVE: linux
    TEST: ci


  
  - SLAVE: windows
    TEST: ruling

  - SLAVE: windows
    SQ_VERSION: DEV

  - SLAVE: windows
    SQ_VERSION: LTS


    
  - SLAVE: multicpu
    SQ_VERSION: DEV
    
  - SLAVE: multicpu
    SQ_VERSION: LTS

  - SLAVE: multicpu
    TEST: ci

  - SLAVE: multicpu
    TEST: plugin