language: node_js

node_js:
  - 'stable'
  - '6'
  - '4'

sudo: false

env:
  - workerCount=3

matrix:
  fast_finish: true

branches:
  only:
  - master
  - release-2.1
  - release-2.2
  - release-2.3

install:
  - npm uninstall typescript
  - npm uninstall tslint
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1
