language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
cache: yarn
matrix:
  allow_failures:
  - node_js: 4
install:
  - npm install -g gulp webpack yarn
  - yarn --pure-lockfile
script:
  - gulp compile:web
  - npm test
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
      - "chat.freenode.net#hearthsim-commits"
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
